[package]
name = "oro-ser2mem"
version.workspace = true
description = "The Oro serialize-to-memory library for the kernel boot protocol"
publish = false
edition = "2021"
authors = [
	"Josh Junon (https//github.com/qix-)"
]
homepage = "https://oro.sh"
repository = "https://github.com/oro-os/kernel"
license = "MPL-2.0"

[dependencies]
oro-ser2mem-macros.workspace = true
