[workspace.package]
description = "The Oro Operating System kernel project"
homepage = "https://oro.sh"
repository = "https://github.com/oro-os/kernel"
license = "MPL-2.0"
version = "0.0.0"

[workspace]
resolver = "2"
members = [
	"oro-acpi",
	"oro-arch",
	"oro-arch-aarch64",
	"oro-arch-x86_64",
	"oro-boot",
	"oro-boot-protocol",
	"oro-bootloader-limine",
	"oro-common",
	"oro-common-assertions",
	"oro-common-proc",
	"oro-common-proc/tests",
	"oro-kernel",
	"oro-serial-pl011",
]

[workspace.dependencies]
oro-acpi = { path = "oro-acpi" }
oro-arch = { path = "oro-arch" }
oro-arch-aarch64 = { path = "oro-arch-aarch64" }
oro-arch-x86_64 = { path = "oro-arch-x86_64" }
oro-boot = { path = "oro-boot" }
oro-boot-protocol = { path = "oro-boot-protocol" }
oro-common = { path = "oro-common" }
oro-common-assertions = { path = "oro-common-assertions" }
oro-common-proc = { path = "oro-common-proc" }
oro-kernel = { path = "oro-kernel" }
oro-serial-pl011 = { path = "oro-serial-pl011" }

oro-acpica-sys = { git = "https://github.com/oro-os/oro-acpica-sys.git", tag = "20240322" }
limine = "0.2.0"
uart_16550 = "0.3.0"
volatile-register = "0.2.2"

syn = { version = "2.0.60", features = ["full"] }
quote = "1.0.36"
proc-macro2 = "1.0.81"
convert_case = "0.6.0"

[workspace.lints.rust]
missing_docs = "warn"

[workspace.lints.rustdoc]
private_doc_tests = "allow"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
missing_docs_in_private_items = "warn"
integer_division = "warn"
module_name_repetitions = "allow"
verbose_bit_mask = "allow"
too_many_lines = "allow"
missing_errors_doc = "allow"
struct_field_names = "allow"

[profile.dev]
panic = "abort"            # Use "abort" panic strategy
debug = "full"             # Full debugging symbols

[profile.release]
opt-level = 3              # Maximum optimizations
lto = "fat"                # Perform LTO across all crates
codegen-units = 1          # Reduce number of codegen units to increase optimizations.
strip = true               # Strip symbols from binary
incremental = false        # Disable incremental building
panic = "abort"            # Use "abort" panic strategy
debug = 0                  # Do not generate debug information

[profile.relwithdebinfo]
inherits = "release"
debug = "full"             # Full debugging symbols
strip = false              # Don't strip symbols from binary
