[package]
name = "oro-ser2mem-macros"
version.workspace = true
description = "Procedural macros for the Oro serialize-to-memory library"
publish = false
edition = "2021"
authors = [
	"Josh Junon (https//github.com/qix-)"
]
homepage = "https://oro.sh"
repository = "https://github.com/oro-os/kernel"
license = "MPL-2.0"

[lib]
proc-macro = true
test = false
bench = false
# FIXME(qix-): workaround for bug: https://github.com/rust-lang/cargo/issues/10368
doc = false

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["full"] }
