[package]
name = "oro-mem"
version.workspace = true
description = "Common memory management utilities for the Oro operating system."
publish = false
edition = "2021"
authors = [
	"Josh Junon (https//github.com/qix-)"
]
homepage = "https://oro.sh"
repository = "https://github.com/oro-os/kernel"
license = "MPL-2.0"

[lib]
doctest = false

[dependencies]
oro-macro.workspace = true
oro-elf.workspace = true
oro-sync.workspace = true
oro-debug.workspace = true

[lints]
workspace = true
