[package]
name = "oro-boot"
version.workspace = true
description = "Boot routine for the Oro kernel"
publish = false
edition = "2021"
authors = [
	"Josh Junon (https//github.com/qix-)"
]
homepage = "https://oro.sh"
repository = "https://github.com/oro-os/kernel"
license = "MPL-2.0"

[lib]
doctest = false

[dependencies]
oro-arch.workspace = true
oro-common.workspace = true
oro-common-assertions.workspace = true
oro-boot-protocol = { workspace = true, features = ["utils"] }
