[package]
name = "oro-kernel"
description = "Oro operating system kernel"
publish = false
edition = "2021"
authors = [
	"Josh Junon (https//github.com/qix-)"
]
homepage = "https://oro.sh"
repository = "https://github.com/oro-os/kernel"
license = "MPL-2.0"

[[bin]]
name = "oro-kernel-x86_64"
path = "bin/x86_64.rs"

[dependencies]
oro-common.workspace = true

[target.'cfg(target_arch = "x86_64")'.dependencies]
oro-arch-x86_64.workspace = true
