name: Build and Lint
on:
  push:
    branches:
      - master
  pull_request:

env:
  RUST_BACKTRACE: full

jobs:
  lint-rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust
      - name: Lint (rustfmt)
        run: cargo fmt --all -- --check
  lint-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust
      - name: Lint (clippy) [common]
        run: cargo oro-clippy-common
      - name: Lint (clippy) [x86_64]
        run: cargo oro-clippy-x86_64
      - name: Lint (clippy) [aarch64]
        run: cargo oro-clippy-aarch64
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust
      - name: Lint (rustdoc)
        run: env RUSTFLAGS="-D warnings" cargo doc --all-features --lib
  build-kernel-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust
      - name: Build
        run: cargo kernel-x86_64
  build-limine-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust
      - name: Build
        run: cargo limine-x86_64
